### ISSUE TITLE
个人信息页与官方略有不同

### ISSUE THREAD

**Issue by PositionZer0** [wangdaye078/AntiZhaPian#3]
1. 身份认证图标不同。官方版（下）相较本应用（上）的边框边距更大一些。
![本应用1](https://user-images.githubusercontent.com/48386601/229745553-7c2fd59a-ffa2-41b5-8ab8-40df56cc9b13.png)
![官方](https://user-images.githubusercontent.com/48386601/229745783-3c48aa37-0672-4de0-a82d-72ea8979af9e.jpg)

2. 所在地区、注册地区的分割号不同。官方版没有“.”作为不同级别地区的分割号，而本应用有。
![本应用2](https://user-images.githubusercontent.com/48386601/229746886-7e053788-976e-4df8-82b3-c183978a29df.jpg)

**Comment by wangdaye078** [comment]
更新
